"use client";
import { useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, ChevronRight, X } from "lucide-react";
import { ankleAssessmentConfig, ankleDomainLabels, ankleStatusLabels, calculateSideDifference, getAnkleDomainStatuses, type AnkleAssessment, type AnkleDomainStatus } from "@/lib/ankle-assessment";
const domains = ["tolerance", "rom", "strength", "control", "performance"] as const;
type Domain = (typeof domains)[number];
const statusOrder: Record<AnkleDomainStatus, number> = { priority: 0, finding: 1, adequate: 2, incomplete: 3 };
const tasks = ["Caminar", "Subir escaleras", "Bajar escaleras", "Ponerse de puntillas", "Sentadilla", "Zancada", "Correr", "Saltar", "Aterrizar", "Cambiar de dirección", "Estar mucho tiempo de pie", "Otra"];
const emptyAssessment = (): AnkleAssessment => ({ id: `ankle-${Date.now()}`, date: new Date().toISOString().slice(0, 10), anchorTask: "", rom: { left: null, right: null }, strength: { left: null, right: null }, control: { anteriorLeft: null, anteriorRight: null, posteromedialLeft: null, posteromedialRight: null, posterolateralLeft: null, posterolateralRight: null }, performance: { left: null, right: null } });
function numberOrNull(value: string) { const parsed = Number(value); return value.trim() && Number.isFinite(parsed) ? parsed : null; }
function tone(status: AnkleDomainStatus) { return status === "priority" ? "border-red-200 bg-red-50/60 text-red-700" : status === "finding" ? "border-amber-200 bg-amber-50 text-amber-800" : status === "adequate" ? "border-moss/20 bg-mint text-moss" : "border-line bg-panel text-ink/50"; }
function summary(status: AnkleDomainStatus) { return status === "priority" ? "Conviene revisar antes de progresar." : status === "finding" ? "Hay información útil para contextualizar." : status === "adequate" ? "Datos completos sin hallazgos relevantes." : "Abre el dominio para registrar datos."; }
function Pair({ disabled, label, left, onChange, right }: {
    disabled: boolean;
    label: string;
    left: number | null;
    right: number | null;
    onChange: (side: "left" | "right", value: number | null) => void;
}) {
    const difference = calculateSideDifference(right, left);
    return <div className="rounded-md border border-line bg-panel/35 p-3"><p className="text-sm font-semibold text-ink">{label}</p><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs font-semibold text-ink/55">Derecho<input className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 text-sm disabled:bg-panel" disabled={disabled} min="0" onChange={(event) => onChange("right", numberOrNull(event.target.value))} type="number" value={right ?? ""}/></label><label className="text-xs font-semibold text-ink/55">Izquierdo<input className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 text-sm disabled:bg-panel" disabled={disabled} min="0" onChange={(event) => onChange("left", numberOrNull(event.target.value))} type="number" value={left ?? ""}/></label></div><p className="mt-2 text-xs text-ink/50">Diferencia: {difference.absolute ?? "—"} · Asimetría: {difference.asymmetryPct === null ? "—" : `${difference.asymmetryPct}%`}</p></div>;
}
function YesNo({ children, disabled, onChange, value }: {
    children: ReactNode;
    disabled: boolean;
    onChange: (value: boolean | undefined) => void;
    value?: boolean;
}) {
    return <label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_220px]"><span>{children}</span><select className="h-10 rounded-md border border-line bg-white px-3 disabled:bg-panel" disabled={disabled} onChange={(event) => onChange(event.target.value ? event.target.value === "yes" : undefined)} value={value === undefined ? "" : value ? "yes" : "no"}><option value="">Sin responder</option><option value="yes">Sí</option><option value="no">No</option></select></label>;
}
function normalizedControlSummary(control: AnkleAssessment["control"]) {
    if (!control.legLengthRight || !control.legLengthLeft)
        return null;
    const normalized = (value: number | null, length: number) => value === null ? "—" : `${Math.round((value / length) * 100)}%`;
    return `Anterior ${normalized(control.anteriorRight, control.legLengthRight)} / ${normalized(control.anteriorLeft, control.legLengthLeft)} · Posteromedial ${normalized(control.posteromedialRight, control.legLengthRight)} / ${normalized(control.posteromedialLeft, control.legLengthLeft)} · Posterolateral ${normalized(control.posterolateralRight, control.legLengthRight)} / ${normalized(control.posterolateralLeft, control.legLengthLeft)}`;
}
export function CoachAnkleAssessment({ assessment, clientName, history, onClose, onSave, readOnly = false }: {
    assessment?: AnkleAssessment;
    clientName: string;
    history: AnkleAssessment[];
    onClose: () => void;
    onSave?: (value: AnkleAssessment) => void;
    readOnly?: boolean;
}) {
    const [draft, setDraft] = useState(() => assessment ?? emptyAssessment());
    const [domain, setDomain] = useState<Domain | null>(null);
    const [safetyOpen, setSafetyOpen] = useState(Boolean(assessment?.safetyFlag || assessment?.safetyNote));
    const [advancedOpen, setAdvancedOpen] = useState(Boolean(assessment?.performance.advancedTest));
    const statuses = useMemo(() => getAnkleDomainStatuses(draft), [draft]);
    const sorted = [...domains].sort((a, b) => statusOrder[statuses[a]] - statusOrder[statuses[b]]);
    const previous = history.find((item) => item.id !== draft.id);
    const update = <K extends keyof AnkleAssessment>(key: K, value: AnkleAssessment[K]) => setDraft((current) => ({ ...current, [key]: value }));
    return <div aria-modal="true" className="assessment-modal-overlay" role="dialog"><section className="assessment-modal-panel max-h-[92vh] max-w-3xl overflow-y-auto">
    <header className="assessment-modal-header sticky top-0 z-10 flex items-start justify-between gap-4 px-5 py-4"><div><p className="text-xs font-semibold uppercase text-moss">Valoración funcional breve</p><h2 className="text-xl font-semibold text-ink">Tobillo v1 · {clientName}</h2><p className="mt-1 text-sm text-ink/55">{readOnly ? `Valoración del ${draft.date}` : "Lectura orientativa para apoyar la decisión del entrenador."}</p></div><button aria-label="Cerrar valoración de tobillo" className="grid size-9 place-items-center rounded-md border border-line bg-white" onClick={onClose} type="button"><X size={18}/></button></header>
    <div className="assessment-modal-body grid gap-4 px-5 py-5">
      {domain === null ? <>
        <section className="rounded-md border border-line bg-panel/25 p-3"><button className="flex w-full items-center justify-between text-left" onClick={() => setSafetyOpen((open) => !open)} type="button"><span><span className="block text-sm font-semibold text-ink">Filtro inicial de seguridad</span><span className="mt-1 block text-xs text-ink/50">¿Hay signos de alarma o motivos para detener / derivar la valoración?</span></span><span className="text-xs font-semibold text-ink/50">{draft.safetyFlag === undefined ? "Sin responder" : draft.safetyFlag ? "Sí" : "No"}</span></button>{safetyOpen ? <div className="mt-3 grid gap-3 border-t border-line pt-3"><p className="text-xs text-ink/50">Hematoma importante, inflamación muy marcada, imposibilidad clara de apoyo, dolor desproporcionado u otros síntomas que hagan prudente parar o derivar.</p><select className="h-10 rounded-md border border-line bg-white px-3 text-sm" disabled={readOnly} onChange={(event) => update("safetyFlag", event.target.value === "" ? undefined : event.target.value === "yes")} value={draft.safetyFlag === undefined ? "" : draft.safetyFlag ? "yes" : "no"}><option value="">Sin responder</option><option value="no">No</option><option value="yes">Sí</option></select>{draft.safetyFlag ? <label className="text-sm font-semibold text-ink">Observación de seguridad<textarea className="mt-1 min-h-16 w-full rounded-md border border-line bg-white p-3 text-sm font-normal" disabled={readOnly} onChange={(event) => update("safetyNote", event.target.value)} value={draft.safetyNote ?? ""}/></label> : null}</div> : null}</section>
        <section className="grid gap-3"><div><h3 className="text-lg font-semibold text-ink">Resumen Tobillo</h3><p className="mt-1 text-sm text-ink/55">Abre cada dominio para {readOnly ? "consultar" : "registrar o revisar"} sus datos.</p></div>{sorted.map((item) => <button className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-md border border-line bg-white p-3 text-left hover:bg-panel/40" key={item} onClick={() => setDomain(item)} type="button"><span><span className="font-semibold text-ink">{ankleDomainLabels[item]}</span><span className="mt-1 block text-xs text-ink/50">{summary(statuses[item])}</span></span><span className={`rounded-md border px-2 py-1 text-xs font-semibold ${tone(statuses[item])}`}>{ankleStatusLabels[statuses[item]]}</span><ChevronRight className="text-ink/35" size={17}/></button>)}<p className="rounded-md border border-line bg-panel/35 p-3 text-xs text-ink/55">{ankleAssessmentConfig.note}</p></section>
        <label className="text-sm font-semibold text-ink">Nota del entrenador<textarea className="mt-1 min-h-20 w-full rounded-md border border-line bg-white p-3 text-sm font-normal disabled:bg-panel" disabled={readOnly} onChange={(event) => update("notes", event.target.value)} value={draft.notes ?? ""}/></label>
        <div className="flex justify-end gap-2"><button className="rounded-md border border-line bg-white px-4 py-2 text-sm font-semibold" onClick={onClose} type="button">Cerrar</button>{!readOnly && onSave ? <button className="rounded-md bg-ink px-4 py-2 text-sm font-semibold text-white" onClick={() => { onSave(draft); onClose(); }} type="button">Guardar valoración</button> : null}</div>
      </> : <section className="grid gap-4">
        <div className="flex items-center justify-between gap-3"><button className="inline-flex items-center gap-2 text-sm font-semibold text-ink/65" onClick={() => setDomain(null)} type="button"><ArrowLeft size={16}/>Volver al resumen</button><span className={`rounded-md border px-2 py-1 text-xs font-semibold ${tone(statuses[domain])}`}>{ankleStatusLabels[statuses[domain]]}</span></div>
        {domain === "control" && normalizedControlSummary(draft.control) ? <p className="rounded-md border border-line bg-white p-3 text-xs font-semibold text-ink/60">Normalización: {normalizedControlSummary(draft.control)}</p> : null}
        {domain === "tolerance" ? <div className="grid gap-3"><h3 className="font-semibold text-ink">Tolerancia · Tarea problemática</h3><label className="text-sm font-semibold">Tarea problemática<select className="mt-1 h-11 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("anchorTask", event.target.value)} value={draft.anchorTask}><option value="">Selecciona una tarea</option>{tasks.map((item) => <option key={item}>{item}</option>)}</select></label>{draft.anchorTask === "Otra" ? <label className="text-sm font-semibold">¿Qué tarea es?<input className="mt-1 h-11 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("customTask", event.target.value)} value={draft.customTask ?? ""}/></label> : null}<label className="text-sm font-semibold">Estado funcional<select className="mt-1 h-11 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("taskStatus", (event.target.value || undefined) as AnkleAssessment["taskStatus"])} value={draft.taskStatus ?? ""}><option value="">Sin responder</option><option value="normal">Puede hacerla sin molestia</option><option value="discomfort">Puede hacerla con molestia</option><option value="avoids">La evita / no puede hacerla</option></select></label>{draft.taskStatus === "discomfort" || draft.taskStatus === "avoids" ? <><label className="text-sm font-semibold">Modificación<select className="mt-1 h-11 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("regression", event.target.value)} value={draft.regression ?? ""}><option value="">Sin responder</option>{["Reducir carga", "Reducir ROM", "Cambiar variante o soporte", "Reducir velocidad", "Reducir impacto"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-semibold">Respuesta tras modificar<select className="mt-1 h-11 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("regressionResponse", (event.target.value || undefined) as AnkleAssessment["regressionResponse"])} value={draft.regressionResponse ?? ""}><option value="">Sin responder</option><option value="better">Mejor</option><option value="same">Igual</option><option value="worse">Peor</option></select></label></> : null}</div> : null}
        {domain === "rom" ? <div className="grid gap-3"><h3 className="font-semibold">ROM · Knee-to-Wall Test</h3><Pair disabled={readOnly} label="Distancia (cm)" left={draft.rom.left} right={draft.rom.right} onChange={(side, value) => update("rom", { ...draft.rom, [side]: value })}/><label className="text-sm font-semibold">¿Modificar la demanda de dorsiflexión mejora claramente la tarea problemática?<select className="mt-1 h-11 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("rom", { ...draft.rom, taskImproves: (event.target.value || undefined) as AnkleAssessment["rom"]["taskImproves"] })} value={draft.rom.taskImproves ?? ""}><option value="">Sin responder</option><option value="yes">Sí</option><option value="no">No</option><option value="inconclusive">No concluyente</option></select></label><p className="text-xs text-ink/50">{previous ? `Histórico disponible: ${previous.date}.` : "Primera medición; el histórico aparecerá en el retest."}</p></div> : null}
        {domain === "strength" ? <div className="grid gap-3"><h3 className="font-semibold">Fuerza · Single-Leg Heel Raise</h3><Pair disabled={readOnly} label="Repeticiones" left={draft.strength.left} right={draft.strength.right} onChange={(side, value) => update("strength", { ...draft.strength, [side]: value })}/><YesNo disabled={readOnly} onChange={(value) => update("strength", { ...draft.strength, consistentHeight: value })} value={draft.strength.consistentHeight}>¿Alcanza una altura consistente?</YesNo><YesNo disabled={readOnly} onChange={(value) => update("strength", { ...draft.strength, maintainsRom: value })} value={draft.strength.maintainsRom}>¿Mantiene un ROM similar hasta el final?</YesNo><YesNo disabled={readOnly} onChange={(value) => update("strength", { ...draft.strength, clearDeviation: value })} value={draft.strength.clearDeviation}>¿Existe desviación clara del talón/tobillo?</YesNo><YesNo disabled={readOnly} onChange={(value) => update("strength", { ...draft.strength, symptomsLimit: value })} value={draft.strength.symptomsLimit}>¿Los síntomas limitan el test?</YesNo><label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_220px]"><span>¿Por qué terminó?</span><select className="h-10 rounded-md border border-line bg-white px-3" disabled={readOnly} onChange={(event) => update("strength", { ...draft.strength, stopReason: event.target.value })} value={draft.strength.stopReason ?? ""}><option value="">Sin responder</option>{["Fatiga local", "Dolor / molestia", "Pérdida de técnica", "Equilibrio", "Otro"].map((item) => <option key={item}>{item}</option>)}</select></label></div> : null}
        {domain === "control" ? <div className="grid gap-3"><h3 className="font-semibold">Control / Estabilidad · Y-Balance Test</h3><Pair disabled={readOnly} label="Longitud de pierna (opcional)" left={draft.control.legLengthLeft ?? null} right={draft.control.legLengthRight ?? null} onChange={(side, value) => update("control", { ...draft.control, [`legLength${side === "left" ? "Left" : "Right"}`]: value })}/>{[["Anterior", "anterior"], ["Posteromedial", "posteromedial"], ["Posterolateral", "posterolateral"]].map(([label, key]) => <Pair disabled={readOnly} key={key} label={label} left={draft.control[`${key}Left` as keyof AnkleAssessment["control"]] as number | null} right={draft.control[`${key}Right` as keyof AnkleAssessment["control"]] as number | null} onChange={(side, value) => update("control", { ...draft.control, [`${key}${side === "left" ? "Left" : "Right"}`]: value })}/>)}<p className="rounded-md bg-panel/50 p-2 text-xs text-ink/50">{draft.control.legLengthRight && draft.control.legLengthLeft ? "Resultados normalizados por longitud de pierna disponibles." : "Sin longitud de pierna registrada; se muestran valores sin normalizar."}</p><YesNo disabled={readOnly} onChange={(value) => update("control", { ...draft.control, lessStable: value })} value={draft.control.lessStable}>¿Sientes este tobillo menos estable?</YesNo><label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_220px]"><span>¿Sientes que el tobillo “se te va”?</span><select className="h-10 rounded-md border border-line bg-white px-3" disabled={readOnly} onChange={(event) => update("control", { ...draft.control, givesWay: (event.target.value || undefined) as AnkleAssessment["control"]["givesWay"] })} value={draft.control.givesWay ?? ""}><option value="">Sin responder</option><option value="never">Nunca</option><option value="occasionally">Ocasionalmente</option><option value="frequently">Frecuentemente</option></select></label><label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_220px]"><span>¿Confías al correr, saltar o cambiar de dirección?</span><select className="h-10 rounded-md border border-line bg-white px-3" disabled={readOnly} onChange={(event) => update("control", { ...draft.control, confidence: (event.target.value || undefined) as AnkleAssessment["control"]["confidence"] })} value={draft.control.confidence ?? ""}><option value="">Sin responder</option><option value="yes">Sí</option><option value="partially">Parcialmente</option><option value="no">No</option></select></label>{statuses.control === "finding" || statuses.control === "priority" ? <p className="rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-800">Profundizar evaluación de estabilidad</p> : null}<p className="text-xs text-ink/45">CAIT reservado para una versión futura.</p></div> : null}
        {domain === "performance" ? <div className="grid gap-3"><h3 className="font-semibold">Performance · Single-Leg Hop</h3><Pair disabled={readOnly} label="Resultado" left={draft.performance.left} right={draft.performance.right} onChange={(side, value) => update("performance", { ...draft.performance, [side]: value })}/>{advancedOpen ? <div className="grid gap-3 rounded-md border border-line bg-panel/25 p-3"><label className="text-sm font-semibold">Test avanzado<select className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("performance", { ...draft.performance, advancedTest: (event.target.value || undefined) as AnkleAssessment["performance"]["advancedTest"] })} value={draft.performance.advancedTest ?? ""}><option value="">Selecciona un test</option><option value="side-hop">Side Hop</option><option value="repeated-hop">Repeated Hop</option><option value="drop-jump">Drop Jump</option></select></label><Pair disabled={readOnly} label="Resultado avanzado" left={draft.performance.advancedLeft ?? null} right={draft.performance.advancedRight ?? null} onChange={(side, value) => update("performance", { ...draft.performance, [`advanced${side === "left" ? "Left" : "Right"}`]: value })}/></div> : !readOnly ? <button className="w-fit rounded-md border border-dashed border-line px-3 py-2 text-sm font-semibold text-ink/65" onClick={() => setAdvancedOpen(true)} type="button">+ Test avanzado</button> : null}<p className="text-xs text-ink/50">{previous ? `Histórico disponible: ${previous.date}.` : "Primera medición; el histórico aparecerá en el retest."}</p></div> : null}
        <button className="mt-2 w-fit rounded-md border border-line bg-white px-4 py-2 text-sm font-semibold" onClick={() => setDomain(null)} type="button">Volver al resumen</button>
      </section>}
    </div>
  </section></div>;
}
