"use client";

import { useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, ChevronRight, X } from "lucide-react";
import { FunctionalPainMap } from "@/components/coach/functional-pain-map";
import {
  calculateHipDifference,
  getHipDomainStatuses,
  hipAssessmentConfig,
  hipDomainLabels,
  hipStatusLabels,
  type HipAssessment,
  type HipDomain,
  type HipDomainStatus,
  type HipSharedPerformance,
  type HipStrengthPattern,
  type HipTask
} from "@/lib/hip-assessment";

const domains: HipDomain[] = ["tolerance", "rom", "strength", "control", "performance"];
const statusOrder: Record<HipDomainStatus, number> = { priority: 0, finding: 1, adequate: 2, incomplete: 3 };
const painLocations = ["Anterior / ingle", "Anterolateral", "Lateral", "Posterolateral / glútea", "Posterior", "Cara interna / aductores", "Difusa / difícil de localizar", "Otra"];
const taskLabels: Record<HipTask, string> = { squat: "Sentadilla", splitSquat: "Zancada / split squat", hinge: "Bisagra de cadera", singleLeg: "Apoyo unilateral" };
const strengthLabels: Record<HipStrengthPattern, string> = { abduction: "Abducción", adduction: "Aducción", extension: "Extensión", flexion: "Flexión" };
const hipMapPoints = [
  { height: 18, label: "Anterior / ingle", view: "front" as const, width: 28, x: 36, y: 42 },
  { height: 22, label: "Anterolateral", view: "front" as const, width: 22, x: 24, y: 39 },
  { height: 23, label: "Lateral", view: "front" as const, width: 18, x: 18, y: 40 },
  { height: 22, label: "Cara interna / aductores", view: "front" as const, width: 22, x: 39, y: 50 },
  { height: 24, label: "Posterolateral / glútea", view: "posterior" as const, width: 27, x: 22, y: 36 },
  { height: 24, label: "Posterior", view: "posterior" as const, width: 34, x: 33, y: 39 }
];

function emptyStrength() { return { method: undefined, unit: "", right: null, left: null }; }
function emptyAssessment(): HipAssessment {
  return {
    id: `hip-${Date.now()}`,
    date: new Date().toISOString().slice(0, 10),
    tolerance: {},
    rom: { flexionRight: null, flexionLeft: null, internalRotationRight: null, internalRotationLeft: null, externalRotationRight: null, externalRotationLeft: null },
    strength: { abduction: emptyStrength(), adduction: emptyStrength(), extension: emptyStrength(), flexion: emptyStrength() },
    control: {}
  };
}
function numberOrNull(value: string) { const parsed = Number(value); return value.trim() && Number.isFinite(parsed) ? parsed : null; }
function tone(status: HipDomainStatus) { return status === "priority" ? "border-orange-200 bg-orange-50 text-orange-800" : status === "finding" ? "border-amber-200 bg-amber-50 text-amber-800" : status === "adequate" ? "border-moss/20 bg-mint text-moss" : "border-line bg-panel text-ink/50"; }
function dot(status: HipDomainStatus) { return status === "priority" ? "bg-orange-500" : status === "finding" ? "bg-amber-500" : status === "adequate" ? "bg-moss" : "bg-ink/25"; }
function summary(status: HipDomainStatus) { return status === "priority" ? "Conviene revisar antes de progresar." : status === "finding" ? "Hallazgo a considerar en planificación." : status === "adequate" ? "Datos completos sin hallazgos relevantes." : "Abre el dominio para registrar datos."; }

function Pair({ disabled, label, left, onChange, right, unit = "°" }: { disabled: boolean; label: string; left: number | null; right: number | null; unit?: string; onChange: (side: "left" | "right", value: number | null) => void }) {
  const difference = calculateHipDifference(right, left);
  return <div className="rounded-md border border-line bg-panel/35 p-3"><p className="text-sm font-semibold text-ink">{label}</p><div className="mt-3 grid grid-cols-2 gap-2">{(["right", "left"] as const).map((side) => <label className="text-xs font-semibold text-ink/55" key={side}>{side === "right" ? "Derecha" : "Izquierda"}<span className="relative mt-1 block"><input className="h-10 w-full rounded-md border border-line bg-white px-3 pr-10 text-sm disabled:bg-panel" disabled={disabled} min="0" onChange={(event) => onChange(side, numberOrNull(event.target.value))} type="number" value={(side === "right" ? right : left) ?? ""}/><span className="absolute right-3 top-2.5 text-xs text-ink/45">{unit}</span></span></label>)}</div><p className="mt-2 text-xs text-ink/50">Diferencia: {difference.absolute ?? "—"} {difference.absolute === null ? "" : unit} · Asimetría: {difference.asymmetryPct === null ? "—" : `${difference.asymmetryPct}%`}</p></div>;
}
function YesNo({ children, disabled, onChange, value }: { children: ReactNode; disabled: boolean; onChange: (value: boolean | undefined) => void; value?: boolean }) {
  return <label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_220px]"><span>{children}</span><select className="h-10 rounded-md border border-line bg-white px-3" disabled={disabled} onChange={(event) => onChange(event.target.value ? event.target.value === "yes" : undefined)} value={value === undefined ? "" : value ? "yes" : "no"}><option value="">Sin responder</option><option value="yes">Sí</option><option value="no">No</option></select></label>;
}

export function CoachHipAssessment({ assessment, clientName, history, onClose, onSave, readOnly = false, sharedPerformance }: { assessment?: HipAssessment; clientName: string; history: HipAssessment[]; onClose: () => void; onSave?: (value: HipAssessment) => void; readOnly?: boolean; sharedPerformance?: HipSharedPerformance | null }) {
  const [draft, setDraft] = useState(() => assessment ?? emptyAssessment());
  const [domain, setDomain] = useState<HipDomain | null>(null);
  const [safetyOpen, setSafetyOpen] = useState(Boolean(assessment?.safetyFlag || assessment?.safetyNote));
  const statuses = useMemo(() => getHipDomainStatuses(draft, sharedPerformance), [draft, sharedPerformance]);
  const sorted = [...domains].sort((a, b) => statusOrder[statuses[a]] - statusOrder[statuses[b]]);
  const previous = history.find((item) => item.id !== draft.id);
  const selectedLocations = draft.painLocations ?? [];
  const update = <K extends keyof HipAssessment>(key: K, value: HipAssessment[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const findings = sorted.filter((item) => statuses[item] === "priority" || statuses[item] === "finding").slice(0, 2);
  const overall = draft.safetyFlag ? "priority" : sorted.map((item) => statuses[item]).sort((a, b) => statusOrder[a] - statusOrder[b])[0];

  return <div aria-modal="true" className="assessment-modal-overlay" role="dialog"><section className="assessment-modal-panel max-h-[92vh] max-w-3xl overflow-y-auto">
    <header className="assessment-modal-header sticky top-0 z-10 flex items-start justify-between gap-4 px-5 py-4"><div><p className="text-xs font-semibold uppercase text-moss">Valoración funcional breve</p><h2 className="text-xl font-semibold text-ink">Cadera v1 · {clientName}</h2><p className="mt-1 text-sm text-ink/55">{readOnly ? `Valoración del ${draft.date}` : "Lectura orientativa para apoyar la decisión del entrenador."}</p></div><button aria-label="Cerrar valoración de cadera" className="grid size-9 place-items-center rounded-md border border-line bg-white" onClick={onClose} type="button"><X size={18}/></button></header>
    <div className="assessment-modal-body grid gap-4 px-5 py-5">
      {domain === null ? <>
        <section className="grid gap-3 rounded-md border border-line bg-white p-3"><div><p className="text-sm font-semibold text-ink">Localización</p><p className="mt-1 text-xs text-ink/50">Selecciona una o varias zonas, sin asociarlas a un diagnóstico.</p></div><label className="text-sm font-semibold text-ink">Lado<select className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("painSide", (event.target.value || undefined) as HipAssessment["painSide"])} value={draft.painSide ?? ""}><option value="">Sin especificar</option><option value="right">Derecha</option><option value="left">Izquierda</option><option value="bilateral">Bilateral</option></select></label><div className="flex flex-wrap gap-1.5">{painLocations.map((location) => { const selected = selectedLocations.includes(location); return <button className={`rounded-full border px-2 py-1 text-[11px] font-semibold ${selected ? "border-moss/30 bg-mint text-moss" : "border-line bg-white text-ink/55"}`} disabled={readOnly} key={location} onClick={() => update("painLocations", selected ? selectedLocations.filter((item) => item !== location) : [...selectedLocations, location])} type="button">{location}</button>; })}</div>{selectedLocations.includes("Otra") ? <input className="h-10 rounded-md border border-line bg-white px-3 text-sm" disabled={readOnly} onChange={(event) => update("customPainLocation", event.target.value)} placeholder="Otra localización" value={draft.customPainLocation ?? ""}/> : null}<FunctionalPainMap disabled={readOnly} frontImageSrc="/body-maps/hip-front.png" imageAlt="Mapa orientativo de cadera" onValuesChange={(values) => update("painLocations", values)} points={hipMapPoints} posteriorImageSrc="/body-maps/hip-posterior.png" values={selectedLocations}/></section>
        <section className="rounded-md border border-line bg-panel/25 p-3"><button className="flex w-full items-center justify-between gap-3 text-left" onClick={() => setSafetyOpen((open) => !open)} type="button"><span><span className="block text-sm font-semibold text-ink">Safety</span><span className="mt-1 block text-xs text-ink/50">Filtro separado de los dominios puntuables.</span></span><span className="text-xs font-semibold text-ink/50">{draft.safetyFlag === undefined ? "Sin responder" : draft.safetyFlag ? "Revisar" : "Sin flags"}</span></button>{safetyOpen ? <div className="mt-3 grid gap-3 border-t border-line pt-3"><p className="text-xs text-ink/50">Traumatismo importante reciente, incapacidad marcada para apoyar, síntomas neurológicos importantes, dolor intenso no relacionado con movimiento/carga o síntomas sistémicos.</p><select className="h-10 rounded-md border border-line bg-white px-3 text-sm" disabled={readOnly} onChange={(event) => update("safetyFlag", event.target.value === "" ? undefined : event.target.value === "yes")} value={draft.safetyFlag === undefined ? "" : draft.safetyFlag ? "yes" : "no"}><option value="">Sin responder</option><option value="no">No</option><option value="yes">Sí</option></select>{draft.safetyFlag ? <><p className="rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-800">Considera valoración adicional / derivación si procede.</p><textarea className="min-h-16 rounded-md border border-line bg-white p-3 text-sm" disabled={readOnly} onChange={(event) => update("safetyNote", event.target.value)} placeholder="Observación de seguridad" value={draft.safetyNote ?? ""}/></> : null}</div> : null}</section>
        <section className="grid gap-3"><div className="rounded-md border border-line bg-white p-3"><p className="text-xs font-semibold uppercase text-ink/45">Estado general</p><p className="mt-1 text-lg font-semibold text-ink">{hipStatusLabels[overall]}</p>{findings.length ? <p className="mt-1 text-sm text-ink/60">{findings.map((item) => hipDomainLabels[item]).join(" · ")}</p> : null}</div>{sorted.map((item) => <button className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-md border border-line bg-white p-3 text-left hover:bg-panel/40" key={item} onClick={() => setDomain(item)} type="button"><span><span className="font-semibold text-ink">{hipDomainLabels[item]}</span><span className="mt-1 block text-xs text-ink/50">{summary(statuses[item])}</span></span><span className={`inline-flex items-center gap-1.5 rounded-md border px-2 py-1 text-xs font-semibold ${tone(statuses[item])}`}><span className={`size-2 rounded-full ${dot(statuses[item])}`}/>{hipStatusLabels[statuses[item]]}</span><ChevronRight className="text-ink/35" size={17}/></button>)}<p className="rounded-md border border-line bg-panel/35 p-3 text-xs text-ink/55">{hipAssessmentConfig.note}</p></section>
        <details className="rounded-md border border-line bg-white"><summary className="cursor-pointer px-3 py-2.5 text-sm font-semibold text-ink">Notas</summary><div className="border-t border-line p-3"><textarea className="min-h-20 w-full rounded-md border border-line bg-white p-3 text-sm" disabled={readOnly} onChange={(event) => update("notes", event.target.value)} value={draft.notes ?? ""}/></div></details>
        <div className="flex justify-end gap-2"><button className="rounded-md border border-line bg-white px-4 py-2 text-sm font-semibold" onClick={onClose} type="button">Cerrar</button>{!readOnly && onSave ? <button className="rounded-md bg-ink px-4 py-2 text-sm font-semibold text-white" onClick={() => { onSave(draft); onClose(); }} type="button">Guardar valoración</button> : null}</div>
      </> : <section className="grid gap-4"><div className="flex items-center justify-between gap-3"><button className="inline-flex items-center gap-2 text-sm font-semibold text-ink/65" onClick={() => setDomain(null)} type="button"><ArrowLeft size={16}/>Volver al resumen</button><span className={`rounded-md border px-2 py-1 text-xs font-semibold ${tone(statuses[domain])}`}>{hipStatusLabels[statuses[domain]]}</span></div>
        {domain === "tolerance" ? <div className="grid gap-3"><div><h3 className="font-semibold text-ink">Tolerancia</h3><p className="mt-1 text-xs text-ink/50">Registra cómo tolera cuatro tareas principales.</p></div>{(Object.keys(taskLabels) as HipTask[]).map((task) => <label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_240px]" key={task}><span>{taskLabels[task]}</span><select className="h-10 rounded-md border border-line bg-white px-3" disabled={readOnly} onChange={(event) => update("tolerance", { ...draft.tolerance, [task]: event.target.value || undefined })} value={draft.tolerance[task] ?? ""}><option value="">Sin responder</option><option value="normal">La realiza sin molestia</option><option value="discomfort">Molestia / afecta a la tarea</option><option value="avoids">La evita / no puede realizarla</option></select></label>)}</div> : null}
        {domain === "rom" ? <div className="grid gap-3"><div><h3 className="font-semibold text-ink">ROM</h3><p className="mt-1 text-xs text-ink/50">Rotaciones registradas en una posición consistente, preferiblemente 90° de flexión, para facilitar el retest.</p></div><Pair disabled={readOnly} label="Flexión de cadera" left={draft.rom.flexionLeft} right={draft.rom.flexionRight} onChange={(side, value) => update("rom", { ...draft.rom, [`flexion${side === "left" ? "Left" : "Right"}`]: value })}/><Pair disabled={readOnly} label="Rotación interna" left={draft.rom.internalRotationLeft} right={draft.rom.internalRotationRight} onChange={(side, value) => update("rom", { ...draft.rom, [`internalRotation${side === "left" ? "Left" : "Right"}`]: value })}/><Pair disabled={readOnly} label="Rotación externa" left={draft.rom.externalRotationLeft} right={draft.rom.externalRotationRight} onChange={(side, value) => update("rom", { ...draft.rom, [`externalRotation${side === "left" ? "Left" : "Right"}`]: value })}/><details className="rounded-md border border-line bg-white"><summary className="cursor-pointer px-3 py-2.5 text-sm font-semibold">Extensión · opcional</summary><div className="border-t border-line p-3"><Pair disabled={readOnly} label="Extensión de cadera" left={draft.rom.extensionLeft ?? null} right={draft.rom.extensionRight ?? null} onChange={(side, value) => update("rom", { ...draft.rom, [`extension${side === "left" ? "Left" : "Right"}`]: value })}/></div></details><label className="text-sm font-semibold">¿El hallazgo afecta a una tarea?<select className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("rom", { ...draft.rom, affectsTask: (event.target.value || undefined) as HipAssessment["rom"]["affectsTask"] })} value={draft.rom.affectsTask ?? ""}><option value="">Sin responder</option><option value="yes">Sí</option><option value="no">No</option><option value="inconclusive">No concluyente</option></select></label><p className="text-xs text-ink/50">{previous ? `Histórico disponible: ${previous.date}.` : "Primera medición; el histórico aparecerá en el retest."}</p></div> : null}
        {domain === "strength" ? <div className="grid gap-3"><div><h3 className="font-semibold text-ink">Fuerza</h3><p className="mt-1 text-xs text-ink/50">Cada patrón usa un mismo método y unidad para ambos lados; así solo se muestra asimetría cuando los datos son comparables.</p></div>{(Object.keys(strengthLabels) as HipStrengthPattern[]).map((pattern) => { const result = draft.strength[pattern]; return <details className="rounded-md border border-line bg-white" key={pattern} open={pattern === "abduction"}><summary className="cursor-pointer px-3 py-2.5 text-sm font-semibold">{strengthLabels[pattern]}</summary><div className="grid gap-3 border-t border-line p-3"><label className="text-sm font-semibold">Método<select className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly} onChange={(event) => update("strength", { ...draft.strength, [pattern]: { ...result, method: event.target.value || undefined } })} value={result.method ?? ""}><option value="">Sin responder</option><option value="dynamometer">Dinamometría</option><option value="load_repetitions">Carga / repeticiones</option><option value="isometric">Test isométrico</option><option value="qualitative">Valoración cualitativa</option></select></label><label className="text-sm font-semibold">Unidad<input className="mt-1 h-10 w-full rounded-md border border-line bg-white px-3 font-normal" disabled={readOnly || result.method === "qualitative"} onChange={(event) => update("strength", { ...draft.strength, [pattern]: { ...result, unit: event.target.value } })} placeholder={result.method === "qualitative" ? "No aplica" : "kg, N, reps..."} value={result.unit ?? ""}/></label><Pair disabled={readOnly} label="Resultado" left={result.left} right={result.right} unit={result.unit || ""} onChange={(side, value) => update("strength", { ...draft.strength, [pattern]: { ...result, [side]: value } })}/><YesNo disabled={readOnly} onChange={(value) => update("strength", { ...draft.strength, [pattern]: { ...result, limitsTask: value } })} value={result.limitsTask}>¿Limita claramente una tarea?</YesNo></div></details>; })}</div> : null}
        {domain === "control" ? <div className="grid gap-3"><div><h3 className="font-semibold text-ink">Control pélvico en apoyo unilateral</h3><p className="mt-1 text-xs text-ink/50">Tarea específica de cadera; evita duplicar el Lateral Step-Down de Rodilla.</p></div>{(["right", "left"] as const).map((side) => <label className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_240px]" key={side}><span>{side === "right" ? "Lado derecho" : "Lado izquierdo"}</span><select className="h-10 rounded-md border border-line bg-white px-3" disabled={readOnly} onChange={(event) => update("control", { ...draft.control, [side]: event.target.value || undefined })} value={draft.control[side] ?? ""}><option value="">Sin responder</option><option value="adequate">Control adecuado</option><option value="mild_compensation">Compensación leve</option><option value="clear_compensation">Compensación clara</option><option value="discomfort">Dolor / molestia</option><option value="not_performed">No realizado</option></select></label>)}</div> : null}
        {domain === "performance" ? <div className="grid gap-3"><div><h3 className="font-semibold text-ink">Performance compartida</h3><p className="mt-1 text-sm text-ink/60">El Single-Leg Hop ya pertenece a Rodilla. Cadera referencia ese resultado sin duplicar la prueba ni sus datos.</p></div>{sharedPerformance ? <div className="rounded-md border border-line bg-white p-3"><p className="text-sm font-semibold">Single-Leg Hop · {sharedPerformance.date}</p><p className="mt-2 text-sm text-ink/65">Derecha {sharedPerformance.right} · Izquierda {sharedPerformance.left}</p><p className="mt-1 text-xs text-ink/50">Asimetría {calculateHipDifference(sharedPerformance.right, sharedPerformance.left).asymmetryPct}% · origen: valoración de Rodilla.</p></div> : <p className="rounded-md border border-line bg-panel/35 p-3 text-sm text-ink/55">Sin un resultado compartido disponible. Registra el test en Rodilla para evitar duplicarlo.</p>}</div> : null}
      </section>}
    </div>
  </section></div>;
}
